FROM bh.cr/balenalabs/bluetooth-%%BALENA_ARCH%%

WORKDIR /usr/src

COPY start.sh /usr/src/

COPY restartpair.sh /usr/src/
RUN chmod a+x /usr/src/restartpair.sh 

CMD [ "/bin/bash", "bluetoothctl >> /shared/logs/bluetooth.logs"]
CMD [ "/bin/bash", "/usr/src/start.sh" ]
