FROM balenalib/raspberry-pi-debian-python:latest

WORKDIR /usr/src

## watch out for those
COPY start.sh /usr/src/

CMD ["/bin/bash", "/usr/src/start.sh"]


# We'll try those later
# COPY requirements.txt ./
# RUN pip install --no-cache-dir -r requirements.txt

# COPY . .

# CMD ["python", "src/main.py"]